# Generated by Django 6.1 on 2026-09-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='link_cgv',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='link_netflix',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_chieu_rap',
            field=models.BooleanField(default=False),
        ),
    ]
