# Generated by Django 6.1 on 2026-09-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_link_cgv_remove_movie_link_netflix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_chieu_rap',
            new_name='On_Air',
        ),
    ]
