# Generated by Django 6.1 on 2026-09-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_is_chieu_rap_movie_on_air'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='On_Air',
        ),
    ]
